INSERT INTO GROCERY_CATEGORY(NAME)
VALUES("DAIRY");

INSERT INTO MEASURING_UNIT(NAME)
VALUES("LITRE");

INSERT INTO GROCERY(NAME, CATEGORY_ID, MEASURING_UNIT_ID, MEASURE, PRICE, DESCRIPTION)
VALUES ("MILK", 1, 1, 1.0, 1.09, "Milk");