CREATE TABLE GROCERY_CATEGORY(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(30)
);

CREATE TABLE MEASURING_UNIT(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE GROCERY(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    MEASURING_UNIT_ID INT NOT NULL,
    MEASURE REAL NOT NULL,
    PRICE REAL NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    IMAGE BLOB,
    FOREIGN KEY (CATEGORY_ID) REFERENCES GROCERY_CATEGORY(ID),
    FOREIGN KEY (MEASURING_UNIT_ID) REFERENCES MEASURING_UNIT(ID)
);

CREATE  TABLE ROLE(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE USERS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PWD_HASH VARCHAR(64) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE LOGIN_HISTORY(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERS_ID INT NOT NULL,
    LAST_LOGIN DATE NOT NULL,
    LAST_IP VARCHAR(15) NOT NULL,
    FOREIGN KEY (USERS_ID) REFERENCES USERS(ID)
);

CREATE TABLE PAYMENT_OPTION(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPTION VARCHAR(20) NOT NULL
);
CREATE TABLE SHOPPING_CART(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERS_ID INT NOT NULL,
    PAYMENT_OPTION_ID INT,
    PURCHASE_DATE DATE,
    FOREIGN KEY (USERS_ID) REFERENCES USERS(ID),
    FOREIGN KEY (PAYMENT_OPTION_ID) REFERENCES PAYMENT_OPTION(ID)
);

CREATE TABLE SHOPPING_HISTORY(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROCERY_ID INT NOT NULL,
    GROCERY_AMOUNT REAL NOT NULL,
    AMOUNT_PRICE REAL NOT NULL,
    SHOPPING_CART_ID INT NOT NULL,
    FOREIGN KEY (GROCERY_ID) REFERENCES  GROCERY(ID),
    FOREIGN KEY (SHOPPING_CART_ID) REFERENCES  SHOPPING_CART(ID)
);
