package hr.grocery.store.grocerystore.model;

public enum GroceryCategoryEnum {
    FRUITS_AND_VEGETABLES, MEAT, FISH, DAIRY,
    OILS_AND_VINEGARS, SPICES, BAKERY, SWEETS_AND_PASTRIES,
    ALCOHOL_DRINKS, NON_ALCOHOL_DRINKS, TOBACCO, CANNED_FOODS,
    COFFEE_AND_TEA, BASIC_FOODSTUFFS, FROZEN_GOODS, HOUSEHOLD_ITEMS
}
